name: chatbot_whatsapp_ai

services:

    evolution-api:
        container_name: evolution_api
        image: evoapicloud/evolution-api:v2.3.7
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - .env
        volumes:
            - evolution_instances:/evolution/instances
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    postgres:
        container_name: postgres_chat
        image: postgres:15
        command: ["postgres", "-c", "max_connections=1000"]
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: evolution
        volumes:
            - postgres_data_chat:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d evolution"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s

    redis:
        container_name: redis
        image: redis:latest
        command: redis-server --port 6379 --appendonly yes
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_chat:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s

    bot:
        container_name: bot
        build: .
        restart: always
        ports:
            - "8090:8000"
        env_file:
            - .env
        volumes:
            - ./vectorstore_data:/app/vectorstore
            - ./rag_files:/app/rag_files
        depends_on:
            evolution-api:
                condition: service_started
            redis:
                condition: service_healthy

volumes:
    evolution_instances:
    postgres_data_chat:
    redis_chat:
